source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'ANAKit_Example', :exclusive => true do
  pod 'ANAKit', :path => '../'
  
end

target 'ANAKit_Tests', :exclusive => true do
  pod 'ANAKit', :path => '../'
end
